In [7]:
import numpy as np

In [8]:
print(np.arange(10))

[0 1 2 3 4 5 6 7 8 9]


In [10]:
list=[1,2,3,4,5,6]
arr=np.array(list)
print(arr)

[1 2 3 4 5 6]


In [11]:
print(arr.reshape(2,3))

[[1 2 3]
 [4 5 6]]


In [12]:
print(np.eye(3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [13]:
arr = np.array([1, 0, 2, 0, 3, 0, 4])
print(arr)
indices = np.nonzero(arr)
print("Indices of non-zero elements:", indices)

[1 0 2 0 3 0 4]
Indices of non-zero elements: (array([0, 2, 4, 6], dtype=int64),)


In [14]:
a = np.array([1, 2, 3, 4, 5])
b = np.array([1, 4, 3, 7, 8])
index = np.where(a == b)
print(index)

(array([0, 2], dtype=int64),)


In [23]:
arr=np.random.randint(1, 101, size=10)
print(arr)

[ 11  53  57  87  45  97  33 100  48  44]


In [24]:
print(np.mean(arr))
print(np.max(arr))
print(np.min(arr))

57.5
100
11


In [25]:
arr = np.array([[1, 2], [3, 4], [5, 6]])
print(arr.flatten())

[1 2 3 4 5 6]


In [31]:
a=np.array([1,2,3])
b=np.array([3,4,5])
print(np.hstack((a,b)))
print(np.vstack((a,b)))

[1 2 3 3 4 5]
[[1 2 3]
 [3 4 5]]


In [32]:
a = np.array([[1, 2], [3, 4]])
b = np.array([8, 18])
solution = np.linalg.solve(a,b)
print(solution)

[2. 3.]
